#!/bin/bash
rm -rfv /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/*
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/jvc-spawnkill.user.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/spin.min.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/jquery-1.11.1.min.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/base.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/jquery-plugins.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/Util.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/Message.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/Author.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/Button.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/SlideToggle.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/Modal.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/modules/Module.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/modules/StartSpawnKill.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/modules/QuickResponse.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/modules/Quote.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/modules/InfosPseudo.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/modules/HilightNewTopic.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/modules/Settings.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/ban.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/topic_new.gif /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/carton.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/bronze.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/argent.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/or.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/rubis.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/emeraude.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/diamant.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/saphir.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/female.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/male.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/unknown.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/plus.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/minus.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/link.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/quote.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/mp.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/alert.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/greasemonkey/jvc-spawnkill/images/settings.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
read