#!/bin/bash
rm -rfv /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/*
ln -sv /media/data/www/spawnkill/jvc-spawnkill.user.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/jquery-1.11.1.min.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/base.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/jquery-plugins.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/Util.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/Message.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/Author.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/Button.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/SlideToggle.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/Modal.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/Module.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/StartSpawnKill.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/QuickResponse.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/Quote.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/Shortcuts.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/InfosPseudo.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/HilightNewTopic.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/LastPage.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/Settings.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/EmbedMedia.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/WarnOnNewPost.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/modules/Test.js /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/ban.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/topic_new.gif /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/carton.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/bronze.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/argent.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/or.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/rubis.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/emeraude.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/diamant.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/saphir.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/female.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/male.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/unknown.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/plus.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/minus.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/link.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/quote.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/mp.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/alert.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/link-gray.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/calendar.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/clock.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/settings.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/youtube.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/vimeo.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/dailymotion.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/sondageio.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/image.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/vocaroo.png /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
ln -sv /media/data/www/spawnkill/images/loader.gif /home/dorian/.mozilla/firefox/8ned6ue0.default/gm_scripts/JVC_SpawnKill/
read